# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../uis/main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 600)
        self.dCount = QtWidgets.QLabel(mainWindow)
        self.dCount.setGeometry(QtCore.QRect(500, 460, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dCount.setFont(font)
        self.dCount.setObjectName("dCount")
        self.label_10 = QtWidgets.QLabel(mainWindow)
        self.label_10.setGeometry(QtCore.QRect(110, 340, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(mainWindow)
        self.label_3.setGeometry(QtCore.QRect(660, 310, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.iCount = QtWidgets.QLabel(mainWindow)
        self.iCount.setGeometry(QtCore.QRect(750, 360, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.iCount.setFont(font)
        self.iCount.setObjectName("iCount")
        self.hButton = QtWidgets.QPushButton(mainWindow)
        self.hButton.setGeometry(QtCore.QRect(110, 380, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hButton.setFont(font)
        self.hButton.setObjectName("hButton")
        self.dashboardLabel = QtWidgets.QLabel(mainWindow)
        self.dashboardLabel.setGeometry(QtCore.QRect(380, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dashboardLabel.setFont(font)
        self.dashboardLabel.setText("Dashboard")
        self.dashboardLabel.setObjectName("dashboardLabel")
        self.dButton = QtWidgets.QPushButton(mainWindow)
        self.dButton.setGeometry(QtCore.QRect(410, 500, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dButton.setFont(font)
        self.dButton.setObjectName("dButton")
        self.label_6 = QtWidgets.QLabel(mainWindow)
        self.label_6.setGeometry(QtCore.QRect(110, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(mainWindow)
        self.label_4.setGeometry(QtCore.QRect(650, 140, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(mainWindow)
        self.label_8.setGeometry(QtCore.QRect(660, 360, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(mainWindow)
        self.label_5.setGeometry(QtCore.QRect(410, 410, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(mainWindow)
        self.label_7.setGeometry(QtCore.QRect(410, 460, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.iButton = QtWidgets.QPushButton(mainWindow)
        self.iButton.setGeometry(QtCore.QRect(660, 400, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.iButton.setFont(font)
        self.iButton.setObjectName("iButton")
        self.label_12 = QtWidgets.QLabel(mainWindow)
        self.label_12.setGeometry(QtCore.QRect(740, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.vlanButton = QtWidgets.QPushButton(mainWindow)
        self.vlanButton.setGeometry(QtCore.QRect(650, 230, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.vlanButton.setFont(font)
        self.vlanButton.setObjectName("vlanButton")
        self.label_2 = QtWidgets.QLabel(mainWindow)
        self.label_2.setGeometry(QtCore.QRect(110, 290, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.hCount = QtWidgets.QLabel(mainWindow)
        self.hCount.setGeometry(QtCore.QRect(200, 340, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hCount.setFont(font)
        self.hCount.setObjectName("hCount")
        self.vmButton = QtWidgets.QPushButton(mainWindow)
        self.vmButton.setGeometry(QtCore.QRect(110, 220, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.vmButton.setFont(font)
        self.vmButton.setObjectName("vmButton")
        self.vlanCount = QtWidgets.QLabel(mainWindow)
        self.vlanCount.setGeometry(QtCore.QRect(650, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.vlanCount.setFont(font)
        self.vlanCount.setObjectName("vlanCount")
        self.label = QtWidgets.QLabel(mainWindow)
        self.label.setGeometry(QtCore.QRect(110, 130, 211, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vmCount = QtWidgets.QLabel(mainWindow)
        self.vmCount.setGeometry(QtCore.QRect(210, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.vmCount.setFont(font)
        self.vmCount.setObjectName("vmCount")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Form"))
        self.dCount.setText(_translate("mainWindow", "123"))
        self.label_10.setText(_translate("mainWindow", "Count"))
        self.label_3.setText(_translate("mainWindow", "Images"))
        self.iCount.setText(_translate("mainWindow", "123"))
        self.hButton.setText(_translate("mainWindow", "More Info"))
        self.dButton.setText(_translate("mainWindow", "More Info"))
        self.label_6.setText(_translate("mainWindow", "Count"))
        self.label_4.setText(_translate("mainWindow", "Virtual LAN"))
        self.label_8.setText(_translate("mainWindow", "Count"))
        self.label_5.setText(_translate("mainWindow", "Datastores"))
        self.label_7.setText(_translate("mainWindow", "Count"))
        self.iButton.setText(_translate("mainWindow", "More Info"))
        self.label_12.setText(_translate("mainWindow", "123"))
        self.vlanButton.setText(_translate("mainWindow", "More Info"))
        self.label_2.setText(_translate("mainWindow", "Hosts"))
        self.hCount.setText(_translate("mainWindow", "123"))
        self.vmButton.setText(_translate("mainWindow", "More Info"))
        self.vlanCount.setText(_translate("mainWindow", "Count"))
        self.label.setText(_translate("mainWindow", "Virtual Machines"))
        self.vmCount.setText(_translate("mainWindow", "123"))


